export {
  API_VERSION,
  USER_INTERACTION_KIND,
  userInteractionClient,
  userInteractionImplementation,
  userInteractionProtocol,
  userInteractionSupport,
  validateUserInteractionRequest,
  validateUserInteractionRequirement,
  validateUserInteractionSupport,
} from './index.js'

export type {
  ApprovalDetail,
  ApprovalInput,
  ApprovalRequest,
  ApprovalValue,
  ConfirmQuestionField,
  PresentationRequestContext,
  PresentationInvocationScope,
  PresentationResult,
  QuestionAnswers,
  QuestionField,
  QuestionOption,
  QuestionRequest,
  QuestionInput,
  SecretInput,
  SecretInputRequest,
  SecretInputValue,
  SelectQuestionField,
  TextQuestionField,
  UserInteractionClient,
  UserInteractionHandler,
  UserInteractionLimits,
  UserInteractionOperation,
  UserInteractionRequest,
  UserInteractionRequirementSpec,
  UserInteractionSupportSpec,
  UserInteractionValue,
} from './index.js'
